// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var MathJs = require("./math.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

console.log(MathJs.double(2));

console.log(MathJs.double(2.3));

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -933331896,
    "click"
  ],
  /* tuple */[
    -833670555,
    "view"
  ]
];

function pricingToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray);
}

function pricingFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray, param);
}

function treatClick(param) {
  return true;
}

function getOtherGeorges(georges) {
  return /* record */[
          /* id */"2",
          /* name */georges[/* name */1]
        ];
}

var f = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var georges = /* record */[
  /* id */"1",
  /* name */"Georges"
];

exports.f = f;
exports.pricingToJs = pricingToJs;
exports.pricingFromJs = pricingFromJs;
exports.treatClick = treatClick;
exports.georges = georges;
exports.getOtherGeorges = getOtherGeorges;
/*  Not a pure module */
